version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esData:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
volumes:
  esData:
    driver: local

#docker-machine ssh
# sudo sysctl -w vm.max_map_count=262144
# {
#   "settings": {
#     "index": {
#       "number_of_shards": 2,
#       "number_of_replicas": 1 # More if do not want to lose data
#     }
#   }
# }